# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerpower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evapotranspiration',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
