# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerpower', '0005_auto_20161209_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='air_temperature',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='light',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
