# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerpower', '0006_auto_20161209_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='air_temperature',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
    ]
