# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerpower', '0007_auto_20161219_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='capture_datetime_utc',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
