# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20161118_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='field_book',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
