# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20161121_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='field_book',
            field=models.CharField(max_length=255),
        ),
    ]
