# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20161123_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='persons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
