# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20161206_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
