# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20161207_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='persons',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
