# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20170418_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('persons', models.IntegerField(blank=True, default='0', null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.AddField(
            model_name='workday',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
