# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='CultureNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nno3', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('nnh4', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('p', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('k', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('ca', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mg', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('sso4', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('b', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('cu', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('fe', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mn', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mo', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('zn', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='DayPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('depositWaterUsed', models.DecimalField(blank=True, decimal_places=0, default='1', max_digits=5, null=True)),
                ('waterUsed', models.DecimalField(blank=True, decimal_places=0, default='1', max_digits=5, null=True)),
                ('timeIrrigation', models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=10, null=True)),
                ('percentageFertilizer', models.DecimalField(blank=True, decimal_places=0, default='100', max_digits=3, null=True)),
                ('fertilizerPerHour', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fertilizer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ecIrrigation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fertilizationTimes', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DayPortionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.DecimalField(blank=True, decimal_places=3, default='0', max_digits=10)),
                ('dayPortion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.DayPortion')),
            ],
        ),
        migrations.CreateModel(
            name='FieldNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nno3', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('nnh4', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('p', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('k', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('ca', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mg', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('sso4', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('b', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('cu', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('fe', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mn', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mo', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('zn', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='FieldNeedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.DecimalField(blank=True, decimal_places=3, default='0', max_digits=10)),
                ('qtAppliedSum', models.DecimalField(blank=True, decimal_places=3, default='0', max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldProductSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nno3', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('nnh4', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('p', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('k', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('ca', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mg', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('sso4', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('b', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('cu', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('fe', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mn', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('mo', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('zn', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterPerHour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fertilizerPerHour', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=255)),
                ('days', models.DurationField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=255)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('nno3', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('nnh4', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('p', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('k', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ca', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('mg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('sso4', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('b', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('cu', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('fe', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('mn', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('mo', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('zn', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('ec', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('solubility', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('price_per_kilo', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fieldproductsum',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Period'),
        ),
        migrations.AddField(
            model_name='fieldneedproducts',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Period'),
        ),
        migrations.AddField(
            model_name='fieldneedproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Product'),
        ),
        migrations.AddField(
            model_name='fieldneed',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Period'),
        ),
        migrations.AddField(
            model_name='dayportionproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Product'),
        ),
        migrations.AddField(
            model_name='dayportion',
            name='irrigationSystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.IrrigationSystem'),
        ),
        migrations.AddField(
            model_name='dayportion',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Period'),
        ),
        migrations.AddField(
            model_name='cultureneed',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilize.Period'),
        ),
    ]
